/* FOR文*/
CREATE OR REPLACE PROCEDURE PROC_SAMPLE
IS
 
BEGIN
    FOR i IN 1..10 LOOp
        DBMS_OUTPUT.PUT_LINE('カウント' || i);
    END LOOP;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error');
END;
/

BEGIN 
    PROC_SAMPLE();
END;
/