CREATE TABLE emp (
  emp_no  VARCHAR2(10),
  emp_sex VARCHAR2(1)
);

INSERT INTO emp VALUES ('001', '1');
INSERT INTO emp VALUES ('002', '2');

CREATE OR REPLACE PROCEDURE PROC_SAMPLE IS
  w_EMPNO VARCHAR2(10) := '001';
  w_SEX   VARCHAR2(1);
BEGIN
  SELECT emp_sex INTO w_SEX FROM emp WHERE emp_no = w_EMPNO;

  IF w_SEX = '1' THEN
    DBMS_OUTPUT.PUT_LINE('男');
  ELSIF w_SEX = '2' THEN
    DBMS_OUTPUT.PUT_LINE('女');
  ELSE
    DBMS_OUTPUT.PUT_LINE('不明');
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/

ALTER SESSION SET NLS_LANGUAGE='Japanese';

SELECT * FROM HR.EMPLOYEES;

BEGIN
  DBMS_OUTPUT.PUT_LINE('Hello, Live SQL!');
END;
/