/* ストアドプロシージャのサンプル*/
CREATE OR REPLACE PROCEDURE PROC_GET_INFO (
    IN_NO    IN VARCHAR,
    OUT_INFO OUT VARCHAR
) IS
    CURSOR C1 IS SELECT * FROM EMP;
BEGIN
    FOR REC IN C1 LOOP
        IF REC.EMP_NO = IN_NO THEN
            OUT_INFO := TO_CHAR(REC.EMP_BIRTHDAY, 'YYYY');
        END IF;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE(OUT_INFO || '年生まれ');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error');
END;
/

BEGIN
    PROC_GET_INFO('002', :OUT_INFO);
END;
/