-- ① EMPテーブルを作成
CREATE TABLE EMP (
    EMP_NO        VARCHAR2(10) PRIMARY KEY,
    EMP_NAME      VARCHAR2(50),
    EMP_BIRTHDAY  DATE
);

-- ② サンプルデータを投入
INSERT INTO EMP VALUES ('001', '佐藤太郎', TO_DATE('1990-04-15', 'YYYY-MM-DD'));
INSERT INTO EMP VALUES ('002', '鈴木花子', TO_DATE('1985-11-30', 'YYYY-MM-DD'));
INSERT INTO EMP VALUES ('003', '田中一郎', TO_DATE('2000-07-09', 'YYYY-MM-DD'));

COMMIT;

SELECT * FROM EMP;

ALTER TABLE EMP
ADD EMP_SEX VARCHAR2(10);

UPDATE EMP SET EMP_SEX = '1' WHERE EMP_NO = '001';
UPDATE EMP SET EMP_SEX = '2' WHERE EMP_NO = '002';
UPDATE EMP SET EMP_SEX = '0' WHERE EMP_NO = '003';